### ISSUE TITLE
Typo in README: "Docker Content Trust" is DCT not DTC

### ISSUE THREAD

**Issue by NotTheEconomist** [bitnami/bitnami-docker-metallb-speaker#2]
**Description**

Typo in README.md

**Steps to reproduce the issue:**

n/a

**Describe the results you received:**

"Docker Content Trust (DTC)"

**Describe the results you expected:**

"Docker Content Trust (DCT)"

**Additional information you deem important (e.g. issue happens only occasionally):**

I'll submit a PR fixing the typo momentarily

**Version**

b579f7d6cafaefcb9237b056edfda8424a3c6601

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by joancafom** [comment]
Thank you so much for your issue and PR, we appreciate it so much!
