### ISSUE TITLE
Update to MetalLB v0.9.5

### ISSUE THREAD

**Issue by invidian** [bitnami/bitnami-docker-metallb-speaker#4]
MetalLB v0.9.5 is out, repo should be updated.

**Comment by javsalgar** [comment]
Hi,

The container is available. Please let us know if you find any issues with it. 

https://github.com/bitnami/bitnami-docker-metallb-controller/commit/d5450b9fbd2d23a2484fdd89dd8b81074117f815

**Comment by invidian** [comment]
Works well, thanks!
