### ISSUE TITLE
Missing v0.10.0 image update

### ISSUE THREAD

**Issue by alex1989hu** [bitnami/bitnami-docker-metallb-speaker#5]
**Description**

**Steps to reproduce the issue:**

MetalLB Controller has been [updated](https://github.com/bitnami/bitnami-docker-metallb-controller/commit/fc4af029506f5a4a91bd016324d6c585f26cf3e6) to `v0.10.0` but MetalLB Speaker remains `v0.9.x`.

**Describe the results you received:**

There is no MetalLB Speaker image with `v0.10.0`.

**Describe the results you expected:**

Having MetalLB Speaker image with `v0.10.0`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
N/A
```

- Output of `docker info`:

```
N/A
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
N/A

**Comment by juan131** [comment]
Thanks for reporting it @alex1989hu ! Let me check why there's no new release of the `0.10.0` version.

I'll come back to you in a few minutes

**Comment by juan131** [comment]
There was an issue in our tests that was preventing the new version to be released. I fixed the test, and it was immediately released after that, see:

- https://hub.docker.com/layers/bitnami/metallb-speaker/0.10.0-debian-10-r0/images/sha256-9f098a2afaa37f5df78eeef53ae9e1629540b4f43c79230b0d59ab07ccd9bcaa
- https://github.com/bitnami/bitnami-docker-metallb-speaker/commit/3564b7bd2cd296f590e371f3695de49b2648cfa5

Thanks so much for reporting the issue @alex1989hu !
