### ISSUE TITLE
Add support for arm/arm64

### ISSUE THREAD

**Issue by rgl** [bitnami/bitnami-docker-metallb-speaker#6]
### Name and Version

docker.io/bitnami/metallb-speaker:0.11.0-debian-10-r74

### What is the problem this feature will solve?

I want to be able to run metallb in the arm64 arch (in particular, in raspberry pi 4/rpi4).

### What is the feature you are proposing to solve the problem?

Support multi-arch like the upstream is publishing multi-arch images at https://hub.docker.com/r/metallb/speaker/tags?page=1&name=v

**Comment by rgl** [comment]
Oh, this seems to be a global issue, related to https://github.com/bitnami/charts/issues/7305

**Comment by carrodher** [comment]
Hi, yes, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
